timesheet/apps/admin_app/urls.py
from django.urls import path
from apps.admin_app.planinha import exportar_hierarquia_para_excel
from .views import AdminView, GerarRelatorioView

app_name = 'admin_app'

urlpatterns = [
    path('', AdminView.as_view(), name='hub'),
    path('relatorio/', GerarRelatorioView.as_view(), name='gerar_relatorio'),
    path("exportar-hierarquia/", exportar_hierarquia_para_excel, name="exportar_hierarquia"),
]

timesheet/apps/user_app/urls.py
from django.urls import path
from .views import GerenciarAtividadesView

app_name = 'user_app'

urlpatterns = [
    path('', GerenciarAtividadesView.as_view(), name='home'),
]

timesheet/core/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.base_app.views import CustomLoginView, SemAcessoView, LogoutAction

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', CustomLoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutAction.as_view(), name='logout'),
    path('sem-acesso/', SemAcessoView.as_view(), name='semAcesso'),

    path('user-base/', include('apps.user_app.urls')),
    path('admin-base/', include('apps.admin_app.urls')),
    path('atividade/', include('apps.atividade_app.urls', namespace='atividade_app')),
]

timesheet/templates/partials/_aside.html
{% load static %}

<aside>
  {% if is_admin %}
  <a href="{% url 'admin_app:hub' %}">
{% elif is_user %}
  <a href="{% url 'user_app:home' %}">
{% else %}
  <a href="#">
{% endif %}
 <!--    <img src="{% static 'partials/img/Branca.svg' %}" alt="o-dome" id="logo-dome">-->
</a>
    <div class="aside-content">
        <ul class="aside-ul-content">
            {% for icon in aside_icons %}
            {% if icon.is_admin and is_admin %}
                 <li><a href="{{ icon.link }}"><i data-feather="{{ icon.icon_name }}" class="left-icons"></i></a></li>
            {% elif icon.is_user and is_user %}
                 <li><a href="{{ icon.link }}"><i data-feather="{{ icon.icon_name }}" class="left-icons"></i></a></li>
            {% elif not icon.is_admin and not icon.is_user %}
                 <li><a href="{{ icon.link }}"><i data-feather="{{ icon.icon_name }}" class="left-icons"></i></a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</aside>

timesheet/templates/partials/_header.html
{% load static %}

<!-- Header e Nav -->

<header>
    <nav>

        <!-- Parte Esquerda Nav -->

        <div class="div-nav-left">
            <div class="div-menu-left">
                {% if is_admin %}
                <a href="{% url 'admin_app:hub' %}">
              {% elif is_user %}
                <a href="{% url 'user_app:home' %}">
              {% else %}
                <a href="#">
              {% endif %}
                <img src="{% static 'partials/img/logo-ja-fiz.png' %}" alt="Timesheet" style="height: 50px;">
              </a>
                
            </div>   
        </div>

        <!-- Parte Direita Nav -->

        <div class="div-nav-right">
            <div class="div-user-nav">
                <ul>
                    <li><h1>Olá, {{ user.username|capfirst }}</h1></li>

                            <!-- Formulário Sair-->

                    <form action="{% url 'logout' %}" method="get" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" id="btn-sair">
                            <i data-feather="log-out" id="exit-menu"></i>
                        </button>
                    </form>

                </ul>  
            </div>
            </div>
        </div>
    </nav>
</header>